import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Links } from './components/nav-links'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <Links />
        <main>{children}</main>
      </body>
    </html>
  )
}
